{% set name = "urchin" %}
{% set version = "0.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fishbotics/urchin/archive/refs/tags/v{{ version }}.zip
  sha256: f3dd40c041bfe77b5611552985c7a3f78240777886d2b2a96897cad29dd73991

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - lxml
    - networkx
    - numpy
    - pillow
    - pycollada >=0.6
    - pyribbit >=0.1.46
    - scipy
    - six
    - trimesh
    - pip
    - setuptools
  run:
    - python >=3.6
    - lxml
    - networkx
    - numpy
    - pillow
    - pycollada >=0.6
    - pyribbit >=0.1.46
    - scipy
    - six
    - trimesh

test:
  imports:
    - urchin
  commands:
    - pip check
  requires:
    - pip
    - libgl  # [linux]

about:
  home: https://github.com/fishbotics/urchin
  summary: URDF parser and manipulator for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
