{% set name = "urchin" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fishbotics/urchin/archive/refs/tags/v{{ version }}.zip
  sha256: bda308ed7d2b80eb1e097dc3963fabe9e00a6cbd89a1f6be6f063c2a065d3671

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - lxml
    - networkx
    - numpy
    - pillow
    - pycollada >=0.6
    - pyribbit >=0.1.46
    - scipy
    - six
    - trimesh
    - pip
  run:
    - python >=3.6
    - lxml
    - networkx
    - numpy
    - pillow
    - pycollada >=0.6
    - pyribbit >=0.1.46
    - scipy
    - six
    - trimesh

test:
  imports:
    - urchin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fishbotics/urchin
  summary: URDF parser and manipulator for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
